schema_version = "1.0.0"

id = "Auto_Purge"
version = "1.0.0"
name = "Auto Purge"
tagline = "Auto Purge Button"
maintainer = "BlenderFace"
type = "add-on"

blender_version_min = "4.2.0"
blender_version_max = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
